### ISSUE TITLE
BUG parser

### ISSUE THREAD

**Issue by Paulo-21** [aig-hagen/taas-fargo#1]
Hello, I have tested your approximate solver and found a bug that can occur when the file has some empty lines at the end of it. This happens with the instance "crusti_g2io_350_0.5_255_40.af"  from iccma23 for exemple.

An empty string is given to  `this->arguments2ids[arg_name1]` and this->arguments2ids[arg_name2] it always return 0 whith it.
so then you are adding a loop for the first argument of the AF.

I made a pull request with a fix if you want.

**Comment by matthiasthimm** [comment]
Merged, thanks!
